server:
  port: 8087

debug: true

spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  session:
    store-type: redis
  redis:
    database: 6
    host: jinx
    port: 6379
    password: 123456
    pool:
      max-active: 10
      max-idle: 8
      max-wait: 50
      min-idle: 5

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/d?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&tinyInt1isBit=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        format_sql: true